development:
  adapter: postgresql
  encoding: utf8
  database: tutorial_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: tutorial_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: tutorial_production
  pool: 5
  username: 
  password: